// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgN2SE851ManNoxKY53HkUfK4zfkeHbkg',
    appId: '1:793736163919:android:15024c92084cb9491fb03a',
    messagingSenderId: '793736163919',
    projectId: 'testing-apps-3f87b',
    storageBucket: 'testing-apps-3f87b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoa1XMC3INufYV1WQUAUZpNQqDPZvK0Yk',
    appId: '1:793736163919:ios:17868d2fd1819de11fb03a',
    messagingSenderId: '793736163919',
    projectId: 'testing-apps-3f87b',
    storageBucket: 'testing-apps-3f87b.appspot.com',
    androidClientId: '793736163919-vdegcgh1kbfld8ut08hblsmq8h6vd37a.apps.googleusercontent.com',
    iosClientId: '793736163919-qss3tqplo2ubcnfdoqbno2drq93b2bep.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
